---
driver:
  name: vagrant
  customize:
    memory: 2048

transport:
  name: rsync

provisioner:
  hosts: test-kitchen
  name: ansible_playbook
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_verbosity: 1
  ansible_verbose: true
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  requirements_path: requirements.yml
  requirements_collection_path: requirements.yml
  http_proxy: <%= ENV['ANSIBLE_PROXY'] %>
  idempotency_test: true
  additional_copy_path:
    - extra_modules
    - filter_plugins

platforms:
  - name: freebsd-13.0-amd64
    driver:
      box: trombik/ansible-freebsd-13.0-amd64
      box_check_update: false
    driver_config:
      ssh:
        shell: '/bin/sh'
# XXX disable forwarded_port due to an issue with ruby 3.x in vagrant
#
# https://github.com/hashicorp/vagrant/issues/12448
# https://github.com/test-kitchen/kitchen-vagrant/issues/459
#      network:
#        - ["forwarded_port", {guest: 80, host_ip: 127.0.0.1, host: 4000}]
    provisioner:
      extra_vars:
        ansible_python_interpreter: '/usr/local/bin/python3'

# XXX on OpenBSD, `rake assets:precompile` fails with:
# libc++abi: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
#
#  - name: openbsd-7.0-amd64
#    driver:
#      box: trombik/ansible-openbsd-7.0-amd64
#      box_check_update: false
#    driver_config:
#      ssh:
#        shell: '/bin/sh'
#    provisioner:
#      extra_vars:
#        ansible_python_interpreter: '/usr/local/bin/python3'

  - name: devuan-4-amd64
    driver:
      box: trombik/ansible-devuan-4-amd64
    provisioner:
      extra_vars:
        ansible_python_interpreter: '/usr/bin/python3'

  - name: debian-11-amd64
    driver:
      box: trombik/ansible-debian-11-amd64
    provisioner:
      extra_vars:
        ansible_python_interpreter: '/usr/bin/python3'

  - name: fedora-35-amd64
    driver:
      box: trombik/ansible-fedora-35-amd64
      box_check_update: false
    provisioner:
      extra_vars:
        ansible_python_interpreter: '/usr/bin/python3'

suites:
  - name: default
    provisioner:
      name: ansible_playbook
      playbook: tests/serverspec/default.yml
    verifier:
      name: shell
      command: rspec -c -f d -I tests/serverspec tests/serverspec/default_spec.rb
