---

collections:
  - name: community.general
  - name: community.postgresql

roles:
  - name: trombik.git
  - name: trombik.postgresql
  - name: trombik.sysctl
  - name: trombik.redis
  - name: trombik.supervisor
  - name: trombik.haproxy
