---

collections:
  - name: community.general
  - name: community.postgresql

roles:
  - name: trombik.git
  - name: trombik.postgresql
    src: https://github.com/trombik/ansible-role-postgresql
    version: master
  - name: trombik.sysctl
  - name: trombik.redis
  - name: trombik.supervisor
  - name: trombik.haproxy
